# Generated by Django 2.0 on 2017-12-21 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pet',
            options={'verbose_name_plural': 'pets'},
        ),
    ]
